image: node:latest

# (Optionnel mais recommandé) — Ne créer un pipeline QUE si AUTH-E2E/ change
workflow:
  rules:
    - changes:
        - AUTH-E2E/**/*
        - .gitlab-ci.yml
      when: always
    - when: never

# Template commun AUTH-E2E
.default_auth_e2e: &auth_e2e
  before_script:
    - cd AUTH-E2E
    - npm ci --cache .npm --prefer-offline
    - npx playwright install --with-deps
  cache:
    key:
      files:
        - AUTH-E2E/package-lock.json
    paths:
      - AUTH-E2E/node_modules/
      - AUTH-E2E/.npm/
  rules:
    - changes:
        - AUTH-E2E/**/*
      when: on_success
    - when: never

# Règles communes
.rules_no_tag_no_release: &rules_no_tag_no_release
  - if: '$CI_COMMIT_TAG'
    when: never
  - if: '$CI_COMMIT_TITLE =~ /^chore: release/'
    when: never
  - changes:
      - AUTH-E2E/**/*
    when: on_success
  - when: never

stages:
  - validate
  - test
  - build
  - release
  - deploy

install:
  stage: .pre
  <<: *auth_e2e
  script:
    - npm ci --cache .npm --prefer-offline

lint:
  stage: validate
  <<: *auth_e2e
  script:
    - npm run lint
  rules: *rules_no_tag_no_release

only-canary:
  stage: validate
  script:
    - echo "Hello Only Canary !"
  rules:
    - if: '$ENV_TARGET == "canary"'
      when: on_success
    - when: never

unit-test:
  stage: test
  <<: *auth_e2e
  script:
    - npm run test:e2e
  rules: *rules_no_tag_no_release

integration-test:
  stage: test
  <<: *auth_e2e
  needs:
    - job: unit-test
      artifacts: false
  script:
    - echo "Hello Integration !"
  rules: *rules_no_tag_no_release

e2e-test:
  stage: test
  <<: *auth_e2e
  needs:
    - job: integration-test
      artifacts: false
  script:
    - echo "Running AUTH-E2E tests..."
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - AUTH-E2E/**/*
      when: on_success
    - when: never

#  BUILD IMAGE DOCKER
build-image:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker image build --platform=linux/amd64 -t $IMAGE_TAG -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE --all-tags
